version: "3.3"

services:

  cassandra1:
    image: cassandra:latest
    ports:
      - "9042:9042"
      - "9160:9160"
    volumes:
      - "cassandra_data_seed:/var/lib/cassandra"
    environment:
      - "CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3"
      - "CASSANDRA_CLUSTER_NAME=Test"
      - "CASSANDRA_DC=eu-central-2"
      # - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
    restart: always

  cassandra2:
    image: cassandra:latest
    ports:
      - "9043:9042"
    volumes:
      - "cassandra_data_1:/var/lib/cassandra"
    environment:
      - "CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3"
      - "CASSANDRA_CLUSTER_NAME=Test"
      - "CASSANDRA_DC=eu-central-2"
      # - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"

  cassandra3:
    image: cassandra:latest
    ports:
      - "9044:9042"
    volumes:
      - "cassandra_data_2:/var/lib/cassandra"
    environment:
      - "CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3"
      - "CASSANDRA_CLUSTER_NAME=Test"
      - "CASSANDRA_DC=eu-central-2"
      # - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
    restart: always

volumes:
  cassandra_data_seed:
  cassandra_data_1:
  cassandra_data_2: